'use strict';

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>'"]/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;'
  })[character]);
}

function formatValue(value, type) {
  if (type === 'money') return Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  if (type === 'quantity') return Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 3 });
  return escapeHtml(value ?? '');
}

function normalizeBranding(branding = {}) {
  return { businessName: String(branding.businessName || 'Holool ERP Enterprise'), logoDataUrl: String(branding.logoDataUrl || ''),
    address: String(branding.address || ''), phone: String(branding.phone || ''),
    secondaryPhone: String(branding.secondaryPhone || ''), email: String(branding.email || '') };
}

const ARABIC_PDF_LABELS = Object.freeze({ 'Sales Invoice': 'فاتورة مبيعات', 'Purchase Invoice': 'فاتورة مشتريات',
  'Purchase Order': 'أمر شراء', Customer: 'العميل', Supplier: 'المورد', Product: 'المنتج', Unit: 'الوحدة',
  Quantity: 'الكمية', 'Unit price': 'سعر الوحدة', Total: 'الإجمالي', Status: 'الحالة', Date: 'التاريخ',
  'Payment method': 'طريقة الدفع', Currency: 'العملة', 'Invoice total': 'إجمالي الفاتورة', 'Base total': 'الإجمالي الأساسي',
  Notes: 'ملاحظات', 'Generated by': 'أُنشئت بواسطة', Description: 'الوصف', 'Order date': 'تاريخ الأمر',
  Expected: 'التسليم المتوقع', 'Supplier reference': 'مرجع المورد', 'Delivery warehouse': 'مستودع الاستلام',
  'Grand total': 'الإجمالي الكلي', Goods: 'البضاعة', 'Additional costs': 'التكاليف الإضافية',
  'Allocated costs': 'التكاليف الموزعة', 'Landed total': 'إجمالي تكلفة الوصول' });
const ARABIC_PDF_EXTRA_LABELS = Object.freeze({
  'Rate to SDG': 'سعر الصرف مقابل الجنيه السوداني', 'Supplier invoice': 'فاتورة المورد',
  'Additional-cost invoices': 'فواتير التكاليف الإضافية', Code: 'الرمز', Type: 'النوع', Amount: 'المبلغ',
  'Base amount': 'المبلغ الأساسي', Phone: 'الهاتف', Location: 'الموقع', 'Not specified': 'غير محدد',
  For: 'عن', 'Prepared by': 'أعد بواسطة', Generated: 'أُنشئ في', Attachment: 'المرفق',
  'Finance approval': 'الاعتماد المالي', DRAFT: 'مسودة', PENDING: 'بانتظار الاعتماد', APPROVED: 'معتمد',
  REJECTED: 'مرفوض', OPEN: 'مفتوح', PARTIALLY_RECEIVED: 'مستلم جزئياً', RECEIVED: 'مستلم', CLOSED: 'مغلق', CANCELLED: 'ملغي',
  'Commercial approval': 'الاعتماد التجاري', 'Financial approval': 'الاعتماد المالي', 'Accounting handoff': 'التسليم للمحاسبة',
  PENDING_COMMERCIAL: 'بانتظار اعتماد المدير التجاري', PENDING_FINANCE: 'بانتظار اعتماد المدير المالي',
  FINANCE_APPROVED: 'معتمد مالياً', COMMERCIAL_REJECTED: 'مرفوض تجارياً', FINANCE_REJECTED: 'مرفوض مالياً'
});
function pdfLabel(locale, value) { return locale === 'ar' ? (ARABIC_PDF_EXTRA_LABELS[value] || ARABIC_PDF_LABELS[value] || value) : value; }
function documentLanguage(locale) { return locale === 'ar' ? 'lang="ar" dir="rtl"' : 'lang="en" dir="ltr"'; }

function brandingStyles() {
  return `.brand-heading { display: flex; align-items: center; gap: 9px; }
    .brand-logo { width: 42px; height: 42px; object-fit: contain; }
    .brand-name { margin: 0 0 4px; font-size: 21px; font-weight: 700; }
    .brand-contact { margin-top: 2px; color: #59677e; font-size: 8px; }`;
}

function buildBrandHeading(branding) {
  const brand = normalizeBranding(branding);
  const contact = [brand.address, [brand.phone, brand.secondaryPhone].filter(Boolean).join(' / '), brand.email].filter(Boolean);
  return `<div class="brand-heading">${brand.logoDataUrl ? `<img class="brand-logo" src="${brand.logoDataUrl}" alt="">` : ''}<div><div class="brand-name">${escapeHtml(brand.businessName)}</div>${contact.map(value => `<div class="brand-contact">${escapeHtml(value)}</div>`).join('')}</div></div>`;
}

function buildReportHtml(report, user, attachments = [], branding = {}) {
  const columns = report.columns || [];
  const headers = columns.map(column => `<th class="${column.type === 'money' || column.type === 'quantity' ? 'num' : ''}">${escapeHtml(column.label)}</th>`).join('');
  const rows = (report.rows || []).map(row => `<tr>${columns.map(column => `<td class="${column.type === 'money' || column.type === 'quantity' ? 'num' : ''}">${formatValue(row[column.key], column.type)}</td>`).join('')}</tr>`).join('');
  const summaries = (report.summary || []).map(item => `<div class="summary"><span>${escapeHtml(item.label)}</span><strong>${formatValue(item.value, item.type)}${item.suffix ? ` ${escapeHtml(item.suffix)}` : ''}</strong></div>`).join('');
  const filterText = report.filterDescription || 'All available records';
  const orientation = report.orientation === 'portrait' ? 'portrait' : 'landscape';
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(report.title)}</title><style>
    @page { size: A4 ${orientation}; margin: 14mm 10mm 15mm; }
    * { box-sizing: border-box; } body { margin: 0; font: 10px Arial, sans-serif; color: #172033; }
    header { display: flex; justify-content: space-between; gap: 20px; border-bottom: 2px solid #2457c5; margin-bottom: 12px; padding-bottom: 9px; }
    h1 { margin: 0 0 4px; font-size: 21px; } h2 { margin: 0; color: #2457c5; font-size: 13px; }
    p { margin: 3px 0; color: #59677e; } .meta { text-align: right; }
    .summaries { display: flex; gap: 8px; margin: 0 0 12px; }
    .summary { min-width: 125px; padding: 8px 10px; border: 1px solid #d8e0ee; border-radius: 5px; background: #f5f8ff; }
    .summary span { display: block; margin-bottom: 3px; color: #657188; font-size: 8px; text-transform: uppercase; }
    .summary strong { font-size: 12px; }
    table { width: 100%; border-collapse: collapse; table-layout: auto; }
    thead { display: table-header-group; } tr { break-inside: avoid; }
    th { background: #eaf0ff; color: #33435e; text-align: left; font-size: 8px; text-transform: uppercase; }
    th, td { border: 1px solid #cdd6e6; padding: 5px 6px; overflow-wrap: anywhere; }
    tbody tr:nth-child(even) { background: #fafbfe; } .num { text-align: right; font-variant-numeric: tabular-nums; }
    .empty { padding: 18px; color: #6b7280; text-align: center; }
    ${brandingStyles()}
    ${attachmentStyles(orientation === 'portrait' ? 245 : 165)}
  </style></head><body>
    <header><div>${buildBrandHeading(branding)}<h2>${escapeHtml(report.title)}</h2><p>${escapeHtml(report.subtitle || '')}</p></div>
      <div class="meta"><p>${escapeHtml(filterText)}</p><p>Generated ${escapeHtml(new Date().toLocaleString('en-GB'))}</p><p>Prepared by ${escapeHtml(user.username)}</p></div></header>
    ${summaries ? `<section class="summaries">${summaries}</section>` : ''}
    <table><thead><tr>${headers}</tr></thead><tbody>${rows || `<tr><td class="empty" colspan="${Math.max(columns.length, 1)}">No records found for the selected filters.</td></tr>`}</tbody></table>
    ${buildAttachmentPages(attachments)}
  </body></html>`;
}

function buildFooterTemplate(report, branding = {}) {
  const brand = normalizeBranding(branding);
  return `<div style="box-sizing:border-box;width:100%;padding:0 10mm;color:#6b7280;font:8px Arial,sans-serif;display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:10px;"><span style="overflow:hidden;white-space:nowrap;text-overflow:ellipsis;">${escapeHtml(brand.businessName)} - ${escapeHtml(report.title)}</span><span>Powered by Holool Tech - Holool.tech</span><span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span></div>`;
}

function attachmentStyles(maxHeightMm) {
  return `.attachment-page { break-before: page; page-break-before: always; text-align: center; }
    .attachment-page h2 { margin: 0 0 7mm; color: #172033; font-size: 14px; }
    .attachment-page img { display: block; max-width: 100%; max-height: ${maxHeightMm}mm; margin: 0 auto; object-fit: contain; }
    .attachment-page p { margin-top: 5mm; color: #59677e; font-size: 9px; }`;
}

function buildAttachmentPages(attachments = [], locale = 'en') {
  return attachments.map((attachment, index) => `<section class="attachment-page"><h2>${pdfLabel(locale, 'Attachment')} ${index + 1}</h2><img src="${attachment.dataUrl}" alt="${escapeHtml(attachment.name)}"><p>${escapeHtml(attachment.name)}</p></section>`).join('');
}

function invoiceStyles(locale = 'en') {
  return `@page { size: A4 portrait; margin: 14mm 12mm 16mm; }
    * { box-sizing: border-box; } body { margin: 0; color: #172033; font: 10px ${locale === 'ar' ? 'Tahoma, Arial' : 'Arial'}, sans-serif; }
    header { display: flex; justify-content: space-between; gap: 16px; padding-bottom: 10px; border-bottom: 2px solid #2457c5; }
    h1 { margin: 0 0 4px; font-size: 22px; } h2 { margin: 0; color: #2457c5; font-size: 14px; }
    h3 { margin: 16px 0 7px; font-size: 12px; } p { margin: 3px 0; color: #59677e; }
    .meta { text-align: right; } .party { margin: 13px 0; padding: 10px 12px; border: 1px solid #d8e0ee; background: #f7f9fd; }
    .party strong { display: block; margin-bottom: 3px; font-size: 12px; }
    table { width: 100%; border-collapse: collapse; } thead { display: table-header-group; } tr { break-inside: avoid; }
    th { color: #33435e; background: #eaf0ff; font-size: 8px; text-align: left; text-transform: uppercase; }
    th, td { padding: 6px; border: 1px solid #cdd6e6; overflow-wrap: anywhere; }
    tbody tr:nth-child(even) { background: #fafbfe; } .num { text-align: right; font-variant-numeric: tabular-nums; }
    .totals { width: 270px; margin: 14px 0 0 auto; } .totals div { display: flex; justify-content: space-between; padding: 6px 8px; border-bottom: 1px solid #d8e0ee; }
    .totals .grand { color: #2457c5; font-size: 13px; font-weight: bold; }
    .notes { margin-top: 14px; padding: 9px 11px; border-left: 3px solid #9bb5eb; background: #f7f9fd; }
    ${brandingStyles()}
    ${locale === 'ar' ? '.meta { text-align: left; } th { text-align: right; } .num { text-align: left; direction:ltr; } .totals { margin:14px auto 0 0; } .notes { border-left:0; border-right:3px solid #9bb5eb; }' : ''}
    ${attachmentStyles(245)}`;
}

function buildSalesInvoiceHtml(invoice, user, attachments = [], branding = {}, locale = 'en') {
  const lines = (invoice.lines || []).map(line => `<tr><td>${escapeHtml(line.product_name)}</td><td>${escapeHtml(line.unit_name)}</td><td class="num">${formatValue(line.quantity, 'quantity')}</td><td class="num">${formatValue(line.unit_price, 'money')} ${escapeHtml(invoice.currency_code)}</td><td class="num">${formatValue(line.line_total, 'money')} ${escapeHtml(invoice.currency_code)}</td></tr>`).join('');
  return `<!doctype html><html ${documentLanguage(locale)}><head><meta charset="utf-8"><title>${pdfLabel(locale, 'Sales Invoice')} ${escapeHtml(invoice.invoice_number)}</title><style>${invoiceStyles(locale)}</style></head><body>
    <header><div>${buildBrandHeading(branding)}<h2>${pdfLabel(locale, 'Sales Invoice')}</h2></div><div class="meta"><p><strong>${escapeHtml(invoice.invoice_number)}</strong></p><p>${escapeHtml(invoice.invoice_date)}</p><p>${pdfLabel(locale, 'Status')}: ${pdfLabel(locale, invoice.status)}</p></div></header>
    <section class="party"><strong>${pdfLabel(locale, 'Customer')}: ${escapeHtml(invoice.customer_name)}</strong><p>${pdfLabel(locale, 'Payment method')}: ${escapeHtml(invoice.payment_method)}</p><p>${pdfLabel(locale, 'Currency')}: ${escapeHtml(invoice.currency_code)} - ${pdfLabel(locale, 'Rate to SDG')}: ${formatValue(invoice.exchange_rate_to_base, 'quantity')}</p></section>
    <table><thead><tr><th>${pdfLabel(locale, 'Product')}</th><th>${pdfLabel(locale, 'Unit')}</th><th class="num">${pdfLabel(locale, 'Quantity')}</th><th class="num">${pdfLabel(locale, 'Unit price')}</th><th class="num">${pdfLabel(locale, 'Total')}</th></tr></thead><tbody>${lines}</tbody></table>
    <section class="totals"><div class="grand"><span>${pdfLabel(locale, 'Invoice total')}</span><strong>${formatValue(invoice.invoice_total, 'money')} ${escapeHtml(invoice.currency_code)}</strong></div><div><span>${pdfLabel(locale, 'Base total')}</span><strong>${formatValue(invoice.invoice_total_base, 'money')} SDG</strong></div></section>
    ${invoice.notes ? `<section class="notes"><strong>${pdfLabel(locale, 'Notes')}</strong><p>${escapeHtml(invoice.notes)}</p></section>` : ''}
    <p>${pdfLabel(locale, 'Generated by')} ${escapeHtml(user.username)} - ${escapeHtml(new Date().toLocaleString(locale === 'ar' ? 'ar-SD' : 'en-GB'))}</p>
    ${buildAttachmentPages(attachments, locale)}</body></html>`;
}

function buildPurchaseInvoiceHtml(invoice, user, attachments = [], branding = {}, locale = 'en') {
  const lines = (invoice.lines || []).map(line => `<tr><td>${escapeHtml(line.product_name)}</td><td>${escapeHtml(line.unit_name)}</td><td class="num">${formatValue(line.quantity, 'quantity')}</td><td class="num">${formatValue(line.unit_price, 'money')}</td><td class="num">${formatValue(line.line_total, 'money')}</td><td class="num">${formatValue(line.allocated_additional_cost, 'money')}</td><td class="num">${formatValue(line.landed_cost_total, 'money')}</td></tr>`).join('');
  const costs = (invoice.costs || []).map(cost => `<tr><td>${escapeHtml(cost.reference_code || '')}</td><td>${escapeHtml(cost.cost_invoice_date || invoice.invoice_date)}</td><td>${escapeHtml(cost.cost_supplier_name)}</td><td>${escapeHtml(cost.cost_type_name)}</td><td class="num">${formatValue(cost.amount, 'money')} ${escapeHtml(cost.currency_code)}</td><td class="num">${formatValue(Number(cost.amount) * Number(cost.exchange_rate_to_base), 'money')} SDG</td></tr>`).join('');
  return `<!doctype html><html ${documentLanguage(locale)}><head><meta charset="utf-8"><title>${pdfLabel(locale, 'Purchase Invoice')} ${escapeHtml(invoice.invoice_code)}</title><style>${invoiceStyles(locale)}</style></head><body>
    <header><div>${buildBrandHeading(branding)}<h2>${pdfLabel(locale, 'Purchase Invoice')}</h2></div><div class="meta"><p><strong>${escapeHtml(invoice.invoice_code)}</strong></p>${invoice.po_number ? `<p>PO: ${escapeHtml(invoice.po_number)}</p>` : ''}${invoice.supplier_invoice_number ? `<p>${locale === 'ar' ? 'فاتورة المورد' : 'Supplier invoice'}: ${escapeHtml(invoice.supplier_invoice_number)}</p>` : ''}<p>${escapeHtml(invoice.invoice_date)}</p><p>${pdfLabel(locale, 'Status')}: ${escapeHtml(invoice.status)}</p></div></header>
    <section class="party"><strong>${pdfLabel(locale, 'Supplier')}: ${escapeHtml(invoice.supplier_name)}</strong><p>${pdfLabel(locale, 'Currency')}: ${escapeHtml(invoice.currency_code)} - ${pdfLabel(locale, 'Rate to SDG')}: ${formatValue(invoice.exchange_rate_to_base, 'quantity')}</p></section>
    <table><thead><tr><th>${pdfLabel(locale, 'Product')}</th><th>${pdfLabel(locale, 'Unit')}</th><th class="num">${pdfLabel(locale, 'Quantity')}</th><th class="num">${pdfLabel(locale, 'Unit price')}</th><th class="num">${pdfLabel(locale, 'Goods')}</th><th class="num">${pdfLabel(locale, 'Allocated costs')}</th><th class="num">${pdfLabel(locale, 'Landed total')}</th></tr></thead><tbody>${lines}</tbody></table>
    ${costs ? `<h3>${pdfLabel(locale, 'Additional-cost invoices')}</h3><table><thead><tr><th>${pdfLabel(locale, 'Code')}</th><th>${pdfLabel(locale, 'Date')}</th><th>${pdfLabel(locale, 'Supplier')}</th><th>${pdfLabel(locale, 'Type')}</th><th class="num">${pdfLabel(locale, 'Amount')}</th><th class="num">${pdfLabel(locale, 'Base amount')}</th></tr></thead><tbody>${costs}</tbody></table>` : ''}
    <section class="totals"><div><span>${pdfLabel(locale, 'Goods')}</span><strong>${formatValue(invoice.goods_total, 'money')} ${escapeHtml(invoice.currency_code)}</strong></div><div><span>${pdfLabel(locale, 'Additional costs')}</span><strong>${formatValue(invoice.additional_cost_total, 'money')} ${escapeHtml(invoice.currency_code)}</strong></div><div class="grand"><span>${pdfLabel(locale, 'Landed total')}</span><strong>${formatValue(invoice.landed_total, 'money')} ${escapeHtml(invoice.currency_code)}</strong></div></section>
    ${invoice.notes ? `<section class="notes"><strong>${pdfLabel(locale, 'Notes')}</strong><p>${escapeHtml(invoice.notes)}</p></section>` : ''}
    <p>${pdfLabel(locale, 'Generated by')} ${escapeHtml(user.username)} - ${escapeHtml(new Date().toLocaleString(locale === 'ar' ? 'ar-SD' : 'en-GB'))}</p>
    ${buildAttachmentPages(attachments, locale)}</body></html>`;
}

function buildPurchaseOrderHtml(order, user, branding = {}, locale = 'en') {
  const brand = normalizeBranding(branding);
  const lines = (order.lines || []).map(line => `<tr><td>${escapeHtml(line.product_name)}</td><td>${escapeHtml(line.description || '')}</td><td class="num">${formatValue(line.ordered_quantity, 'quantity')}</td><td>${escapeHtml(line.unit_name)}</td><td class="num">${formatValue(line.unit_price, 'money')} ${escapeHtml(order.currency_code)}</td><td class="num">${formatValue(line.line_total, 'money')} ${escapeHtml(order.currency_code)}</td></tr>`).join('');
  return `<!doctype html><html ${documentLanguage(locale)}><head><meta charset="utf-8"><title>${pdfLabel(locale, 'Purchase Order')} ${escapeHtml(order.po_number)}</title><style>${invoiceStyles(locale)}
    .notice { margin: 12px 0; padding: 9px; border: 1px solid #e2b34c; background: #fff8e6; color: #684b0b; font-weight: bold; text-align: center; }
    .signatures { display: grid; grid-template-columns: 1fr 1fr; gap: 45px; margin-top: 35px; }
    .signature { padding-top: 28px; border-top: 1px solid #59677e; text-align: center; color: #59677e; }
  </style></head><body>
    <header><div>${buildBrandHeading(brand)}<h2>${pdfLabel(locale, 'Purchase Order')}</h2></div><div class="meta"><p><strong>${escapeHtml(order.po_number)}</strong></p><p>${pdfLabel(locale, 'Status')}: ${pdfLabel(locale, order.approval_state || order.status)}</p><p>${pdfLabel(locale, 'Order date')}: ${escapeHtml(order.order_date)}</p><p>${pdfLabel(locale, 'Expected')}: ${escapeHtml(order.expected_delivery_date || pdfLabel(locale, 'Not specified'))}</p></div></header>
    <div class="notice">${locale === 'ar' ? 'هذا المستند أمر شراء، وليس فاتورة مورد أو إثباتاً لاستلام المخزون.' : 'This document is a Purchase Order. It is not a supplier invoice or proof that stock has been received.'}</div>
    ${order.commercial_approved_by_name ? `<p><strong>${pdfLabel(locale, 'Commercial approval')}:</strong> ${escapeHtml(order.commercial_approved_by_name)} - ${escapeHtml(order.commercial_approved_at || '')}${order.commercial_approval_comment ? ` (${escapeHtml(order.commercial_approval_comment)})` : ''}</p>` : ''}
    ${order.financial_approved_by_name ? `<p><strong>${pdfLabel(locale, 'Financial approval')}:</strong> ${escapeHtml(order.financial_approved_by_name)} - ${escapeHtml(order.financial_approved_at || '')}${order.financial_approval_comment ? ` (${escapeHtml(order.financial_approval_comment)})` : ''}</p>` : ''}
    ${order.accounting_handoff_at ? `<p><strong>${pdfLabel(locale, 'Accounting handoff')}:</strong> ${escapeHtml(order.accounting_handoff_at)}</p>` : ''}
    <section class="party"><strong>${pdfLabel(locale, 'Supplier')}: ${escapeHtml(order.supplier_name)}</strong>${order.supplier_phone ? `<p>${pdfLabel(locale, 'Phone')}: ${escapeHtml(order.supplier_phone)}</p>` : ''}${order.supplier_location ? `<p>${pdfLabel(locale, 'Location')}: ${escapeHtml(order.supplier_location)}</p>` : ''}<p>${pdfLabel(locale, 'Supplier reference')}: ${escapeHtml(order.supplier_reference || pdfLabel(locale, 'Not specified'))}</p><p>${pdfLabel(locale, 'Currency')}: ${escapeHtml(order.currency_code)} - ${pdfLabel(locale, 'Rate to SDG')}: ${formatValue(order.exchange_rate_to_base, 'quantity')}</p><p>${pdfLabel(locale, 'Delivery warehouse')}: ${escapeHtml(order.warehouse_name)}</p></section>
    <table><thead><tr><th>${pdfLabel(locale, 'Product')}</th><th>${pdfLabel(locale, 'Description')}</th><th class="num">${pdfLabel(locale, 'Quantity')}</th><th>${pdfLabel(locale, 'Unit')}</th><th class="num">${pdfLabel(locale, 'Unit price')}</th><th class="num">${pdfLabel(locale, 'Total')}</th></tr></thead><tbody>${lines}</tbody></table>
    <section class="totals"><div class="grand"><span>${pdfLabel(locale, 'Grand total')}</span><strong>${formatValue(order.total, 'money')} ${escapeHtml(order.currency_code)}</strong></div></section>
    ${order.notes ? `<section class="notes"><strong>${pdfLabel(locale, 'Notes')}</strong><p>${escapeHtml(order.notes)}</p></section>` : ''}
    <section class="signatures"><div class="signature">${pdfLabel(locale, 'For')} ${escapeHtml(brand.businessName)}</div><div class="signature">${pdfLabel(locale, 'For')} ${escapeHtml(order.supplier_name)}</div></section>
    <p>${pdfLabel(locale, 'Prepared by')} ${escapeHtml(order.created_by_name || user.username)}. ${pdfLabel(locale, 'Generated')} ${escapeHtml(new Date().toLocaleString(locale === 'ar' ? 'ar-SD' : 'en-GB'))}</p>
  </body></html>`;
}
module.exports = { buildReportHtml, buildFooterTemplate, buildAttachmentPages, attachmentStyles, buildBrandHeading, brandingStyles, buildSalesInvoiceHtml, buildPurchaseInvoiceHtml, buildPurchaseOrderHtml };
